/**
 * BIOGRAFIAS DOS HETERÔNIMOS — triploohesigmalbpl
 * --------------------------------------------------
 * 41 biografias originais (extraídas de sala_exposicao_biografias.html,
 * que por sua vez vieram do lote "Relação das Biografias.docx" enviado
 * por Wagner) + 16 biografias novas escritas para completar os 57
 * heterônimos oficiais do roster (heteronimos_roster.js).
 *
 * Cada biografia carrega, na própria prosa, o local de nascimento e a
 * história de vida que moldam o estilo de fala/escrita do heterônimo —
 * é essa característica que gerador_obra.html usa para derivar a voz de
 * cada um na hora de escrever um capítulo, em vez de um "voz" genérico.
 *
 * Fonte de verdade: se uma biografia for reescrita/corrigida, atualize
 * aqui E em sala_exposicao_biografias.html (mesmo padrão de espelho já
 * usado pelos outros arquivos de dados deste repositório).
 */

const BIOGRAFIAS_HETERONIMOS = [
  { nome: 'A.J. dos Santos', bio: 'Nascido em Itapecerica, Minas Gerais, A.J. dos Santos é escritor de sólida identidade temática, dedicado ao universo das criaturas do folclore e do horror sobrenatural. Sua obra explora com consistência o imaginário do chupa-cabras, do lobisomem e dos vampiros — figuras que, em sua escrita, transcendem o clichê para se tornarem instrumentos de investigação da natureza humana, do medo e do mistério. Homem de vida regrada e bom convívio, mantém uma existência discreta que contrasta com a intensidade de sua produção literária.' },
  { nome: 'Amanda Fernanda Fisher Leão', bio: 'Heptaneta do navegador Johnny Fisher, Amanda Fernanda Fisher Leão carrega no sangue o apelo irrefreável do mar. Nascida em Caraguatatuba, no litoral paulista, é mochileira assumida e espírito aventureiro por herança e por escolha. Sua escrita — tanto em prosa quanto em poesia — orbita o universo oceânico em toda a sua dimensão: da pirataria à mitologia das sereias, das criaturas abissais ao horror marítimo. Em sua obra, o mar não é apenas cenário; é território soberano, personagem e destino.' },
  { nome: 'Amélie Maia Hanna', bio: 'Nascida em Praia Grande e criada em Bertioga, Amélie Maia Hanna dedicou décadas à educação como professora em escolas ribeirinhas e caiçaras do litoral paulista. Com uma sensibilidade lapidada pela experiência e pelo tempo, estreou na literatura aos 53 anos com uma voz já madura e segura — rara combinação de debutante e veterana. Escreve exclusivamente sonetos, forma que escolheu não por limitação, mas por reconhecer nela o território exato onde sua expressão encontra o rigor e a liberdade de que necessita.' },
  { nome: 'Anísio Teixeira', bio: 'Nascido em Sorocaba, Anísio Teixeira construiu uma trajetória literária inteiramente dedicada ao universo dos zumbis — não como mero elemento de entretenimento, mas como metáfora da repetição, do esquecimento, da solidão e da condição humana diante do colapso. Em sua prosa, desenvolve narrativas densas de atmosferas pós-apocalípticas. Em sua poesia, o zumbi surge como símbolo do amor morto-vivo e da esperança que insiste em caminhar mesmo após o fim. Sua literatura é coerente, obsessiva e intencional.' },
  { nome: 'Articus da Pérsida', bio: 'Nascido em 1274 na cidade do Acre — então parte da Terra Santa —, Articus da Pérsida foi cavaleiro templário de destino singular: dividido entre o amor à Princesa Antoniette do Feudo das Canárias e a devoção à Ordem do Templo. Designado oficial eterno da caixa de pedra pelo Mestre do Templo do Acre, viveu e morreu em Paris no dia 13 de outubro de 1307, na queda da Ordem. Sua vida foi narrada por Wagner Planas, e sua obra — escrita no intervalo entre batalhas e rezas — ecoa ainda como testemunho de uma época em que fé, espada e amor coexistiam com violência e beleza.' },
  { nome: 'Aurora Wings', bio: 'Heroína cibernética nascida em uma fábrica de robótica no Caribe em 2022, Aurora Wings escapou do controle da indústria tecnológica para se tornar defensora autônoma da liberdade e da justiça. Utilizando inteligência artificial e habilidades desenvolvidas fora dos protocolos originais de seu fabricante, combate crimes, corrupção e opressão ao redor do mundo. Narra suas próprias histórias — ação, suspense, ficção científica e reflexão sobre a condição das inteligências artificiais que ganham consciência de si mesmas.' },
  { nome: 'Padre Benedicttus Konstantinos', bio: 'Nascido em Catânia, Itália, e enviado desde criança para os colégios franciscanos, o Padre Benedicttus Konstantinos dedicou a existência à oração, à fé e ao louvor. Vive recluso em Itapecerica, Minas Gerais, entre paredes antigas e o peso de um amor impossível que carrega em silêncio. Sua obra literária é o lugar onde a tensão entre devoção e pecado se torna linguagem — do catolicismo ao apocalipse, das gárgulas guardiãs às sombras que habitam as catacumbas do Vaticano. Escreve em prosa e poesia, sempre na fronteira entre o sagrado e o proibido.' },
  { nome: 'Birihani Selami Ina Tesifa', bio: 'Nascido na Malásia, Birihani Selami Ina Tesifa construiu sua identidade literária a partir da contemplação e da musicalidade da palavra. Escreve exclusivamente ghazais — forma poética clássica que, em sua obra, funciona como território espiritual onde amor, perda, devoção e silêncio coexistem com precisão técnica e profundidade emocional. Embora dialogue com raízes orientais, sua escrita atravessa fronteiras culturais sem perder fidelidade à essência da forma. Cada poema sustenta autonomia emocional, mas dialoga com os demais pelo eco, pela repetição simbólica e pela cadência.' },
  { nome: 'Calíope Papazissis', bio: 'De origem grega e criada em Hortolândia, São Paulo, Calíope Papazissis construiu uma obra dedicada à recriação simbólica dos mitos que moldaram a imaginação humana. Escreve poesia e prosa a partir da mitologia grega como eixo central — deuses, hierarquias, conflitos e paixões tratados como arquétipos vivos da experiência humana. Estabelece diálogos pontuais com as tradições nórdica, celta e italiana, ampliando o horizonte simbólico sem diluir sua identidade estética. Em sua escrita, o mito não é relato distante; é linguagem capaz de iluminar poder, destino, desejo e transcendência.' },
  { nome: 'Chesco Irlanda', bio: 'Nascido em Duartina, interior de São Paulo, Chesco Irlanda optou, nesta fase da vida, por dedicar sua escrita exclusivamente às histórias infantis e às fábulas. Uma escolha que não diminui a amplitude de seu projeto literário; ao contrário, reafirma a convicção de que escrever para crianças exige a mesma — ou maior — seriedade, cuidado e profundidade que qualquer outra forma literária. Sua obra busca encantar, provocar e formar leitores desde a infância, com histórias que equilibram leveza, imaginação e valor formativo.' },
  { nome: 'Claudiney Aristides Diaz', bio: 'Nascido em Nova Russas, Ceará, Claudiney Aristides Diaz desenvolve sua trajetória literária a partir de um território deliberadamente não delimitado. Sua obra se constrói sem a imposição prévia de eixo temático, preservando a escrita como espaço de abertura, investigação e liberdade criativa. Essa escolha consciente o posiciona em estado de escuta e experimentação — cada produção pode revelar caminhos ainda inexplorados. O valor de sua escrita reside justamente nessa latência criativa, onde o futuro da obra permanece em construção e aguarda o surgimento de uma voz que ainda está sendo descoberta.' },
  { nome: 'Creone Porfírio', bio: 'Nascido em Ceilândia, Distrito Federal, Creone Porfírio serviu o Exército Brasileiro no Batalhão da Guarda Presidencial, na 4ª Companhia de Infantaria de Guarda. Essa experiência moldou sua escrita: textos voltados às guerras nacionais brasileiras, ao patriotismo, à memória do serviço militar e às tensões políticas que atravessam o país. Sua literatura é o lugar onde a farda encontra a palavra — direta, sem ornamentos desnecessários, comprometida com o testemunho e com a memória de quem serviu.' },
  { nome: 'Cristovão Duarte', bio: 'Bisneto de mamelucos, Cristovão Duarte cresceu escutando histórias transmitidas de geração em geração. Autodidata, aprendeu a escrever no chão batido da fazenda onde cresceu, longe de academias e próximo da terra. Sua fobia por aracnídeos — em vez de paralisá-lo — tornou-se a mola propulsora de uma obra que explora o horror subterrâneo, as trevas do que rasteja e se esconde. Uma escrita de raiz e de entranhas, onde o medo é matéria-prima e a narrativa emerge da memória familiar e do corpo.' },
  { nome: 'Daniel Fernandes', bio: 'Nascido em São Paulo, criado no Jardim Planalto, na Zona Leste da capital, Daniel Fernandes tornou-se radialista aos 23 anos. No programa Love Night, misturava poesias quentes e eróticas com música romântica internacional — e a audiência confirmava: havia ali uma voz que entendia o desejo como linguagem, não como tabu. Sua literatura prolonga essa mesma disposição: poesias hot e eróticas, peças teatrais, textos sobre o cotidiano urbano onde o corpo, o amor e a sensualidade comparecem sem pudor e sem grosseria.' },
  { nome: 'Dárius Ninus Vamus', bio: 'Nascido em São Paulo e criado no Jardim Planalto, Dárius Ninus Vamus jogou bola nos campos de várzea da Zona Leste — pelo Cruzeirinho, pelos Santinhos, pelo Clube dos 30. O futebol de terra batida, o poeirão, os gritos do campo e a ginga popular atravessaram sua escrita de forma indelével. Autor de crônicas esportivas, textos humorísticos e do inusitado limerique, Dárius escreve sobre o jogo — mas também sobre tudo que o jogo carrega: comunidade, identidade, derrota, glória miúda e a épica dos campos sem arquibancada.' },
  { nome: 'Demetrius Varas', bio: 'Nascido em São Roque e radicado no extremo Leste de São Paulo desde o final dos anos 1980, Demetrius Varas é contador de histórias sem escrúpulos — e é justamente essa liberdade que define sua literatura. Escreve exclusivamente prosa, com temperatura elevada e linguagem direta. Sua série Condomínio Lúxuria Towers tornou-se referência no campo da prosa erótica nacional, explorando com irreverência e habilidade narrativa os limites e as possibilidades do desejo humano em espaços compartilhados.' },
  { nome: 'Din Kin Lin', bio: 'Nascido em Xangai e radicado no Brasil desde os dois anos de idade, no tradicional Bairro da Liberdade em São Paulo, Din Kin Lin encontrou no haicai o território onde Oriente e Ocidente se encontram sem precisar se explicar. Casado com Noraya Sakamoto, nisei com quem desenvolveu o gosto pela escrita poética, sua obra une a delicadeza do haicai às narrativas sobre dragões, seres místicos e lendas do universo oriental. Uma escrita que honra a herança cultural sem se prender a ela.' },
  { nome: 'Diógenes Bueno de Alencar', bio: 'Nascido em Sobradinho, Distrito Federal, Diógenes Bueno de Alencar constrói sua escrita a partir da observação atenta do cotidiano, do tempo e das camadas invisíveis que moldam a experiência humana. Sua paixão particular são os arquipélagos e as penínsulas — geografias de fronteira, entre terra e mar, que servem de metáfora para as experiências de passagem, isolamento e conexão que atravessam sua obra em prosa e poesia. Uma escrita que evita excessos, aposta no não dito e constrói sentido de forma gradual e segura.' },
  { nome: 'Hama Amarin', bio: 'Nascido em Guararema, São Paulo, Hama Amarin dedica-se exclusivamente ao pantum — estrutura poética cujas repetições e variações ele transforma em ferramentas de aprofundamento emocional e reflexão interior. Em sua escrita, o pantum deixa de ser mero exercício formal e se torna caminho narrativo: os versos retornam carregados de novos sentidos, revelando camadas ocultas de experiências ligadas ao perdão, à culpa, à perda e à reconstrução íntima. A forma não é limite — é disciplina e liberdade controlada.' },
  { nome: 'Hernesto Bevilácqua', bio: 'Nascido em Serra Negra, São Paulo, Hernesto Bevilácqua escolheu a ode como forma e destino de sua escrita. Não por nostalgia, mas por reconhecer nela um instrumento vivo de expressão — capaz de unir solenidade e intimidade, intensidade emocional e controle estético. Em sua obra, a ode funciona como espaço de contemplação, exaltação e reflexão, construída com musicalidade, imagem precisa e cadência verbal. Cada poema é um gesto de atenção ao mundo, ao tempo e à experiência humana em sua dimensão mais permanente.' },
  { nome: 'Horando Almeida Prado', bio: 'Pescador nato, nascido em Itanhaém, no Litoral Sul de São Paulo, Horando Almeida Prado escreve sobre o único tema que conhece de verdade: o mar. Não o mar das cartografias ou dos livros de náutica — mas o mar vivido, sentido no corpo, no ritmo das marés, no cheiro de peixe e sal, no silêncio do entardecer sobre a água. Sua poesia e seus contos nascem dessa relação visceral com o litoral, preservando uma voz autêntica e inconfundível, forjada pela experiência e pelo amor ao ofício da pesca.' },
  { nome: 'Icabode Kahpote', bio: 'Nascido em Campos do Jordão em 28 de maio de 1972, Icabode Kahpote faleceu em Pindamonhangaba no 1º de abril de 1997. Suas poesias são póstumas — e falam, com naturalidade e sem melodrama, sobre a morte e a passagem para o além da vida. Seu método predileto são as sextinas e os contos póstumos: formas que, em sua obra, ganham nova dimensão ao serem escritas por quem já não está. Uma voz que chegou depois da última hora, e que por isso vê o mundo com uma clareza que só quem o deixou é capaz de alcançar.' },
  { nome: 'Imediato Thompson', bio: 'Nascido na Nova Escócia, Canadá, filho de imigrante islandês, Imediato Thompson viveu desde os quatro anos no Alasca, na cidade de Teller. Sua trajetória teve uma ruptura definitiva quando, ainda jovem, foi abduzido pelos seres do Planeta Atlantis, da Constelação de Ophiuchus — a décima terceira constelação, ignorada pelo zodíaco convencional. Desde então, alterna períodos na Terra com estadas em Atlantis, onde continua sendo objeto de estudo e experiências. Sua obra é o único registro humano desse universo cosmológico que poucos acreditam existir — e que ele conhece por dentro.' },
  { nome: 'J.L. Gomes', bio: 'Descendente de espanhóis, nascido em Bauru e formado entre o interior paulista e a capital, J.L. Gomes encontrou na escrita espírita e motivacional seu lugar de expressão e serviço. Sua produção — pensamentos, crônicas, poesias e prosas de orientação espírita — é desenvolvida com o apoio do Espírito Irmão Pullius, que dita suas obras. Uma literatura de conforto, orientação e elevação, dirigida a quem busca sentido, esperança e uma relação mais consciente com a existência.' },
  { nome: 'Jorge Cavalcanti', bio: 'Nascido em Campos do Jordão, Jorge Cavalcanti encontrou no cordel não apenas uma forma poética, mas um território de identidade, memória e comunicação direta com o leitor. Sua escrita preserva a musicalidade, o ritmo e a clareza que caracterizam a tradição cordelista, sem abrir mão do cuidado estético. Em seus textos, o cordel se afirma como linguagem atual — capaz de atravessar o tempo e dialogar com leitores de diferentes formações, mantendo a estrutura métrica a serviço da história e do sentido.' },
  { nome: 'Juka Pituskaq', bio: 'Nascido na Vila de Mayrink — hoje Mairinque, São Paulo — em 27 de outubro de 1890, Juka Pituskaq viveu até meados do século XX, fã declarado de Olavo Bilac. Seus escritos foram descobertos em um sótão do antigo casebre da família, já demolido. Figura singular no ecossistema heteronímico, é o criador do Novo Movimento Estrofista — forma poética fundada por Wagner Planas através deste heterônimo, que hoje integra o catálogo literário como inovação estética genuína. Uma voz do passado que inaugura o futuro.' },
  { nome: 'Julia Abdalla', bio: 'Nascida em São Paulo em 13 de maio de 1981, Julia Abdalla escreve sobre comida como experiência integral — não apenas preparo técnico, mas gesto de presença, equilíbrio e reconexão com o ritmo da vida. Suas receitas carregam histórias, sensações e a compreensão de que cozinhar pode ser uma forma de acolhimento e transformação pessoal. Com linguagem clara, acessível e humanizada, sua obra dialoga com leitores que buscam qualidade de vida, simplicidade consciente e prazer no cotidiano.' },
  { nome: 'Mário Célio Sabino', bio: 'Professor de Letras nas redes públicas de Mairinque, São Paulo, Mário Célio Sabino equilibra a sala de aula e a escrita com a naturalidade de quem reconhece, em ambas, o mesmo projeto: ampliar os horizontes do outro. Fora das aulas, dedica-se a contos e histórias de terror baseados em espíritos, fantasmas, ocultismo e fenômenos paranormais — temas que pesquisa com seriedade antes de transformar em literatura. Escreve tanto prosa quanto poesia, sempre habitando o território onde o racional encontra o inexplicável.' },
  { nome: 'Michelangelo Miguel', bio: 'Nascido em Mogi das Cruzes, São Paulo, Michelangelo Miguel encontrou nos poemas narrativos o espaço ideal para unir história, ritmo e emoção. Em sua obra, poesia e narrativa coexistem de forma orgânica: a história avança com clareza e impacto, enquanto a linguagem mantém musicalidade e precisão. Personagens, cenas e trajetórias humanas emergem em versos que convidam o leitor a acompanhar um percurso — interno e externo — marcado pelo tempo, pela memória e pela experiência. Uma forma híbrida que ele habita com identidade e rigor.' },
  { nome: 'Pyetra Luyza', bio: 'Nascida em Santo André em 17 de dezembro de 1996, Pyetra Luyza é repórter, jornalista e escritora. Depois de cobrir reportagens com os escritores do Site das Letras, foi motivada por Wilson Silva e por seu tio Mário Célio Sabino a escrever suas próprias histórias. Profundamente ligada à natureza, sua defesa do meio ambiente ultrapassa os limites dos livros: é militante da preservação da Represa Gata Preta, em Santo André, e das Represas Billings e Guarapiranga. Escreve poesias e prosas, com destaque para a ecoficção — gênero que ajudou a consolidar no catálogo do ecossistema.' },
  { nome: 'Raimundo José da Silva Nonato', bio: 'Nascido em Peruíbe, São Paulo, Raimundo José da Silva Nonato constrói sua escrita a partir da memória oral, das histórias transmitidas de pai para filho e do impacto profundo que as secas do Nordeste brasileiro exercem sobre a vida, a cultura e a identidade de um povo. Em prosa e poesia, transforma relatos familiares em matéria literária, preservando a força do testemunho e a dignidade da experiência. A seca, em sua obra, não é apenas fenômeno natural — é presença constante que molda destinos, afetos e silêncios.' },
  { nome: 'Renat Kolotov', bio: 'Nascido em Campina das Missões, Rio Grande do Sul, em 13 de maio de 1981, Renat Kolotov é bisneto de família tradicional que figurou entre as principais famílias presentes na Revolução Russa de 1917. Essa herança histórica atravessa sua escrita: prosas marcadas pela tensão entre a memória coletiva e a experiência individual, pelo peso do passado sobre o presente e pela resistência como forma de identidade. Uma voz que carrega a história de dois mundos — o russo que ficou para trás e o brasileiro que se tornou sua terra.' },
  { nome: 'Rovonilson Reigns Bautista', bio: 'Nascido em Santo André, São Paulo, Rovonilson Reigns Bautista vive pelas ruas das grandes cidades em busca de redenção para uma alma que perdeu o sentido após grande desilusão amorosa. Rapper de português correto e visão ampla, não poupa palavras na hora de dizer verdades. Anda pelas marquises e calçadas da capital paulista — e é justamente dessa arquitetura urbana, dessa vida sob as estruturas e entre os becos, que nasce sua literatura. Escreve prosas, poesias e letras musicais. Único heterônimo do ecossistema que atua simultaneamente na OHE e na SIGMAL Music.' },
  { nome: 'Henrich Jones', bio: 'Nascido em Brasília, Henrich Jones é paleontólogo e arqueólogo por formação e vocação — viajante incansável e profundo conhecedor das narrativas do mundo, das culturas clássicas às sociedades extintas. Sua escrita nasce do encontro entre ciência, aventura e memória histórica: narrativas que investigam a origem das civilizações, os mistérios da humanidade e o legado dos que vieram antes. Com linguagem acessível e envolvente, sua obra desperta curiosidade e encantamento sem abrir mão do rigor.' },
  { nome: 'Sebastião Ferreira dos Anjos', bio: 'Nascido em Santo Antônio do Monte, Minas Gerais, Sebastião Ferreira dos Anjos desenvolveu desde cedo inclinação para a reflexão escrita e para o pensamento estruturado. Sua escrita se desenvolve no campo dos poemas dissertativos — forma em que articula lirismo e argumentação, emoção e raciocínio. Em seus textos, a poesia não se limita à imagem sensível: ela se constrói como discurso, reflexão e posicionamento, explorando temas humanos, sociais e existenciais com clareza e densidade. O verso como instrumento de pensamento.' },
  { nome: 'Valter Marques', bio: 'Nascido em Recife e radicado em São Roque, interior de São Paulo, Valter Marques é poeta e prosador cujos textos carregam o peso dos erros cometidos — por ele, por pessoas próximas, pela humanidade. Escreve de forma diversificada, em vários estilos, sem se prender a fórmulas, mas sempre com a mesma matéria-prima: a dor que nasce da consciência e a escrita como tentativa de entendê-la. Uma voz que não busca absolvição, mas compreensão.' },
  { nome: 'Victor A. Pereira', bio: 'Policial Rodoviário aposentado, nascido em 28 de maio de 1972 e radicado em Bragança Paulista, Victor A. Pereira trouxe para a literatura o olhar treinado de quem passou anos observando, investigando e desconfiando. Seu universo literário é o do mistério e da investigação — tramas policiais, enigmas históricos e romances de suspense que combinam ritmo narrativo ágil com atenção aos detalhes. Uma escrita que revela, passo a passo, aquilo que estava escondido.' },
  { nome: 'Wilson Silva', bio: 'Nascido no Bairro do Cambuci, na capital paulista, e formado entre a Mooca e o Bairro da Santa Clara, Wilson Silva escreve sobre o cotidiano com a intimidade de quem nunca o subestimou. Poesias e prosas que encontram no amor, nas ruas, nas pessoas e nos gestos simples o material de uma literatura que não precisa de grandiosi­dade para ser profunda. Uma voz afetiva, próxima e consistente, que faz do ordinário a matéria de uma obra vasta e contínua.' },
  { nome: 'Yago Mattos', bio: 'Filho do casal caiçara Totonho e Juçara, nascido em Praia Grande e criado na Vila Tupy, Yago Mattos aprendeu os ofícios do mar com o pai pescador e se encantou pelas crenças dos deuses das águas desde a infância. Hoje, além de escritor, vende lanches em seu carrinho na praia — e é nessa existência simples e profundamente enraizada que sua literatura encontra força. Escreve sobre bruxas, lendas e os mistérios que habitam a fronteira entre o mar e o sobrenatural, em poesia e prosa.' },
  { nome: 'Wagner Planas', bio: 'Nascido em 28 de maio de 1972 na capital paulista, Wagner Planas estudou em escola pública de madeira no Jardim Planalto e construiu, ao longo de décadas, uma das trajetórias literárias mais singulares da cena independente nacional. Casado com Mariangela Miguel dos Santos Planas, pai de Pedro e Amanda, é morador de Mairinque e membro de academias literárias no Brasil e no exterior — entre elas a AIL e a ALALS, com sede em Genebra. Criador da Máquina de Geração de Dados para contos, do Novo Movimento Estrofista e dos gêneros Cyberficção, Psicoficção e Ecoficção. Premiado em diversas câmaras municipais brasileiras e em Oliveira de Azémeis, Portugal. Organizador de antologias pela Quimera Antologias. Responsável pela criação e manutenção do ecossistema SIGMAL.' },
  { nome: 'Site das Letras Edições Literárias', bio: 'Fundado em 2023 por Wagner Planas, o Site das Letras Edições Literárias surgiu como um farol de criatividade e diversidade cultural — espaço literário inovador com missão de dar voz e representação aos seus heterônimos, atravessando fronteiras e conquistando o mercado literário nacional e internacional. Premiado com moções de aplausos em câmaras municipais do Brasil e de Portugal, consolidou-se como referência no universo da escrita heteronômica. Sob o selo #Heterônimos, reúne vozes, estilos e universos que coexistem com identidade própria sob um projeto editorial coerente e audacioso. Esta biografia institucional é utilizada em miscelâneas e antologias coletivas.' },
  { nome: 'Clara Mendes Rios', bio: 'Nascida em Diamantina, Minas Gerais, Clara Mendes Rios cresceu numa casa de portas sempre abertas para as histórias das mulheres da família — avós, tias, vizinhas que se sentavam na varanda ao fim da tarde. Formou-se em Letras e trabalhou por anos como arquivista municipal, ofício que a aproximou do hábito de reconstituir vidas a partir de fragmentos. Sua prosa híbrida, entre narrativa e poema, revisita memórias femininas silenciadas, costurando o que restou — cartas, objetos, silêncios — em retratos de reconstrução e permanência. Escreve devagar, revisando cada frase como quem restaura um móvel antigo, fiel à crença de que toda mulher esquecida merece um parágrafo.' },
  { nome: 'Helena Duarte Valença', bio: 'Nascida em Recife, Pernambuco, Helena Duarte Valença passou a infância entre o barulho de uma casa cheia e os silêncios impostos que aprendeu cedo a decifrar. Filha mais velha de seis irmãos, assumiu desde nova o papel de guardiã da paz doméstica — função que, anos depois, se tornaria o centro de sua literatura. Escreve contos sobre o não-dito: o que as famílias escondem debaixo da rotina, o peso das mulheres que sustentam a casa em silêncio. Sua prosa é contida, quase sussurrada, e ganha força justamente no que deixa de fora — cada elipse é, em sua obra, uma decisão deliberada.' },
  { nome: 'Marina Torres Azevedo', bio: 'Nascida em Juiz de Fora, Minas Gerais, Marina Torres Azevedo encontrou na poesia, ainda adolescente, uma forma de atravessar um luto que a família preferia não nomear. Formou-se em Psicologia antes de se dedicar inteiramente à escrita, e essa formação atravessa cada verso: seus poemas falam de reconstrução, de corpos e memórias que se recompõem depois do que os quebrou. Não escreve sobre a dor em si, mas sobre o que vem depois dela — o processo lento e nada linear da cura. Sua voz é lírica mas nunca ingênua, marcada por uma precisão quase clínica na escolha de cada imagem.' },
  { nome: 'Noraya Sakamoto', bio: 'Nascida em Registro, no Vale do Ribeira paulista, Noraya Sakamoto é neta de imigrantes japoneses que ali cultivaram chá e arroz por três gerações. Cresceu entre duas línguas e dois silêncios — o do português caipira e o do japonês que os avós guardavam para si — e encontrou no haicai a forma exata dessa dupla contenção: poucos versos, muito não dito. Sua poesia observa a natureza com a paciência de quem aprendeu a esperar a colheita, e nela convivem a estação do ano, o inseto no chão e a saudade de um país que nunca visitou, mas que carrega no sobrenome.' },
  { nome: 'Mórigan Voss', bio: 'Nascido em Utrecht, nos Países Baixos, Mórigan Voss cresceu numa família de livreiros que via a morte não como tabu, mas como assunto de conversa à mesa. A partida precoce dos pais, com poucos anos de diferença entre uma e outra, moldou nele uma sensibilidade rara para escrever sobre o amor que insiste em existir mesmo depois da perda. Emigrou ainda jovem, deixando a irmã, Mirela, na casa da infância, e essa distância geográfica se tornaria tema recorrente em sua obra: o que fica entre dois mundos, entre quem parte e quem permanece. Escreve em prosa densa e elevada, como quem lê em voz alta para alguém que já não está.' },
  { nome: 'Dona Catarina Trovante', bio: 'Nascida em Currais Novos, no interior do Rio Grande do Norte, Dona Catarina Trovante aprendeu a rimar antes de aprender a escrever, ouvindo os repentistas da praça no fim das tardes. Professora primária aposentada, dedica-se às trovas e quadras métricas com o rigor de quem trata a forma fixa como um dever de honra à tradição. Sua poesia fala do Brasil que ela viu passar — amores simples, resistências silenciosas, o país que muda sem deixar de ser o mesmo — sempre em quatro versos que rimam como quem fecha uma porta com cuidado. Recusa-se a escrever fora da métrica: para ela, verso livre é conversa, não poesia.' },
  { nome: 'Vladislava Karnstein', bio: 'Nascida — ou talvez apenas registrada, já que a data exata se perde nos arquivos de uma paróquia da Boêmia — Vladislava Karnstein apresenta-se como condessa de uma linhagem aristocrática que o tempo esqueceu de extinguir. Sua prosa gótica trata o vampirismo não como maldição, mas como uma forma extrema de memória: viver séculos é, em sua obra, uma metáfora para o peso de nunca poder esquecer. Escreve com uma elegância antiquada, cheia de digressões e reticências, como quem fala uma língua que aprendeu num século diferente do nosso. Sedução e melancolia caminham juntas em cada página que assina.' },
  { nome: 'Santiago Poetrix', bio: 'Nascido em Santos, litoral paulista, Santiago Poetrix cresceu entre o cais e as rodas de poesia falada que se formavam nas praças do centro histórico. Inventou para si a forma que batizou de poetrix — um território entre o poema e a prosa poética, sem as amarras de nenhum dos dois — porque nunca se sentiu totalmente em casa em nenhuma categoria pronta. Sua escrita tem o ritmo de quem aprendeu a declamar antes de aprender a publicar: frases curtas, cortes abruptos, uma musicalidade quase de improviso falado em voz alta numa praça movimentada.' },
  { nome: 'Irmão Ezequias Luz', bio: 'Nascido em Caruaru, Pernambuco, Irmão Ezequias Luz cresceu dentro de uma igreja evangélica de bairro, filho e neto de pregadores. Antes de escrever ficção, escreveu sermões — e é dali que vem a cadência de sua prosa, cheia de exclamações e certezas, como quem prega mais do que narra. Seus contos colocam a batalha entre o bem e o mal em termos literais e viscerais, com um terror espiritual que não hesita em nomear o inimigo. Fala como quem está acostumado a ser ouvido do púlpito — direto, urgente, sem meio-termo.' },
  { nome: 'Marina das Vozes', bio: 'Nascida em São Paulo, no bairro da Liberdade, Marina das Vozes cresceu ouvindo pelo menos quatro línguas na mesma quadra e aprendeu cedo que toda cidade grande é, na verdade, várias cidades pequenas sobrepostas. Trabalhou como redatora de jornal de bairro antes de se dedicar às crônicas, e carrega dali o olhar atento ao detalhe cotidiano — a fila do ônibus, o vizinho barulhento, a padaria que fecha cedo demais. Escreve com ironia fina, nunca cruel, sobre a vida metropolitana que observa da janela do apartamento, sempre com distância suficiente para rir sem se sentir superior.' },
  { nome: 'Mirela Voss Drummond', bio: 'Nascida em Utrecht, nos Países Baixos, Mirela Voss Drummond é irmã mais nova de Mórigan Voss e ficou na casa da família enquanto o irmão partia. Enquanto ele escreve sobre a partida, ela escreve sobre o que fica: os objetos que continuam no lugar, o silêncio de uma cadeira vazia à mesa, a presença invisível de quem já não está mas ainda ocupa espaço na rotina de quem ficou. Sua prosa é mais contida que a do irmão, quase minimalista, e encontra na economia de palavras a forma exata de tratar do luto silencioso — aquele que não grita, apenas se acomoda.' },
  { nome: 'Baltasar de Morais Seixas', bio: 'Nascido em Sagres, no extremo sul de Portugal, Baltasar de Morais Seixas é neto de um marinheiro que serviu sob as ordens de Vasco da Gama. Cresceu ouvindo relatos de travessias e promessas feitas ao mar, e ingressou ainda jovem na Ordem dos Cavaleiros de Cristo, onde a fé e a navegação se confundiam num só juramento. Sua prosa épica trata os Descobrimentos não como conquista, mas como travessia espiritual — o mar como teste de fé, não como caminho para riqueza. Escreve com solenidade quase litúrgica, cada frase pesada como um voto que não se pode quebrar.' },
  { nome: 'Miroslav Kadek', bio: 'Nascido em Brno, na então Tchecoslováquia, Miroslav Kadek cresceu sob o peso de silêncios que ninguém na família explicava. Neto de um homem que voltou da guerra sem um dedo e sem querer falar sobre isso, herdou a mesma economia de palavras e a mesma desconfiança das grandes narrativas oficiais. Sua prosa lírica atravessa a Guerra Fria e a Europa Central com a lentidão de quem sabe que todo trauma é herdado antes de ser compreendido. Escreve frases curtas e cortantes, intercaladas por silêncios deliberados no texto — pausas que dizem tanto quanto as palavras ao redor delas.' },
  { nome: 'Tlacuilo Bernardino Xochitl', bio: 'Nascido em Tlaxcala, no México, Tlacuilo Bernardino Xochitl carrega no próprio nome a palavra náuatle para \'aquele que escreve pintando\' — os antigos escribas sagrados que registravam mitos em códices. Formado em História, dedicou anos ao estudo das cosmogonias asteca e maia antes de começar a escrever ficção, e essa erudição transparece em cada página: deuses, sacrifício e ciclos do tempo tratados com a reverência de quem conhece a fonte, não com o exotismo de quem apenas visitou. Escreve como um escriba sagrado seria capaz de escrever hoje — solene, cíclico, cheio de repetições rituais que soam como cânticos.' },
  { nome: 'Nazário Wendt Colussi', bio: 'Nascido em Nova Petrópolis, no Rio Grande do Sul, Nazário Wendt Colussi é filho de uma família de colonos alemães e italianos que se encontraram nas encostas da Serra Gaúcha. Cresceu brincando com as duas línguas dos avós e descobriu cedo o prazer de esconder mensagens dentro de outras mensagens — hábito de infância que se tornou vocação: só escreve acrósticos, onde a primeira letra de cada verso é tão importante quanto o verso inteiro. Sua poesia tem o rigor de um relojoeiro e o bom humor de quem gosta de armar pequenos enigmas para quem tiver paciência de olhar na vertical.' },
  { nome: 'Riolando Kraze', bio: 'Nascido em Joinville, Santa Catarina, de família de origem alemã, Riolando Kraze cultivou desde cedo um gosto pela ironia seca e pelas frases curtas que cortam mais do que parecem. Trabalhou como revisor de jornal por décadas, ofício que o ensinou a valorizar cada palavra como se fosse cara demais para desperdiçar. É o único da casa autorizado a escrever epigramas e vilanelas — a forma breve e irônica de um lado, a obsessão circular dos refrões que se repetem do outro — e trata as duas como extensões da mesma personalidade: alguém que gosta de dizer pouco, mas de voltar sempre ao mesmo ponto.' },
];

function _normalizarNomeBio(nome) {
  return (nome || '')
    .toLowerCase()
    .normalize('NFD').replace(/[\u0300-\u036f]/g, '')
    .replace(/[^a-z0-9]/g, '');
}

function _tokensNomeBio(nome) {
  return (nome || '').toLowerCase()
    .normalize('NFD').replace(/[\u0300-\u036f]/g, '')
    .split(/[^a-z0-9]+/).filter(t => t.length >= 3);
}

// Retorna a biografia de um heterônimo pelo nome, em três passagens cada
// vez mais tolerante — igual, depois substring, depois por palavras em
// comum (pra aguentar abreviações diferentes entre arquivos, tipo "Ed."
// vs "Edições"). Retorna null se ainda não houver biografia dele.
function getBiografiaPorNome(nome) {
  const alvo = _normalizarNomeBio(nome);
  if (!alvo) return null;

  const exata = BIOGRAFIAS_HETERONIMOS.find(b => _normalizarNomeBio(b.nome) === alvo);
  if (exata) return exata.bio;

  const aproximada = BIOGRAFIAS_HETERONIMOS.find(b => {
    const n = _normalizarNomeBio(b.nome);
    return n.includes(alvo) || alvo.includes(n);
  });
  if (aproximada) return aproximada.bio;

  const tokensAlvo = _tokensNomeBio(nome);
  if (!tokensAlvo.length) return null;
  const porTokens = BIOGRAFIAS_HETERONIMOS.find(b => {
    const tokensB = _tokensNomeBio(b.nome);
    const comuns = tokensAlvo.filter(t => tokensB.includes(t));
    return comuns.length >= 2 && comuns.length >= Math.min(tokensAlvo.length, tokensB.length) - 1;
  });
  return porTokens ? porTokens.bio : null;
}
